import Hero from "@/components/Hero";
import About from "@/components/About";
import Skills from "@/components/Skills";
import Header from "@/components/Header";
import Projects from "@/components/Projects";

import WorkExperience from "@/components/WorkExperience";
import Head from "next/head";
import ContactMe from "@/components/ContactMe";
import Link from "next/link";
// import { Inter } from '@next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory 
    overflow-y-scroll overflow-x-hidden z-0 scrollbar-thin scrollbar-track-gray-400/20
    scrollbar-thumb-[#F7AB0A]/80">
      <Head>
        <title>Rami`s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <section id="hero" className="snap-start">
        <Hero />
      </section>

      <section id="about" className="snap-center">
        <About />
      </section>

      <section id="experience" className="snap-center">
        <WorkExperience />
      </section>

      <section id="skills" className="snap-start">
        <Skills />
      </section>

      <section id="projects" className="snap-start">
        <Projects />
      </section>

      {/* Contact Me */}
      <section id="contact" className="snap-start">
        <ContactMe />
      </section>

      <Link href="#hero">
        <footer className="sticky bottom-5 w-10 cursor-pointer ml-[50%]">
          <div className="flex items-center justify-center">
            <img 
            className="h-10 w-10 rounded-full filter grayscale hover:grayscale-0 cursor-pointer"
            src="https://res.cloudinary.com/dgnco8bh4/image/upload/v1678138364/Portfolio/rami-icon_xr9eko.png" alt="rami logo" />
          </div>
        </footer>
      </Link>
    </div>
  );
}
